### PR TITLE
Fixing images display

### PR DESCRIPTION
**Pull request by lesauf**
Hello Dlacreme,

I do not know, the images were not visible, so I fixed that.

Thank you for the nice code!

Stephane

### CODE REVIEW

**Comment by Dlacreme** [comment]
Hello @lesauf 

Really appreciate your contributions ! Yes I didn't find the right way to import pictures, thanks a lot !

Also please note this was a quick test to see if this is doable but I've noticed errors in the formula that cause incorrect links with complex family tree

**Comment by lesauf** [comment]
Errors in SVG.js or in your algorithms? Please can you describe a bit?

I am glad you already looked at it. I will continue from where you stopped.

**Comment by Dlacreme** [comment]
In my algorithm only. The svg part is working fine.

I probably missed a value somewhere because a gap appears when you have 3 or more familial generation

**Comment by lesauf** [comment]
Ok, I see. Nice! If the contract is concluded I will look into it.

Thank you very much!

**Pull request merged**
